baseURL = "https://k8s-school.fr/"
languageCode = "fr-fr"
title = "K8s-school"
themesDir = "themes"
theme = "hugo-serif-theme"
enableRobotsTXT = true

[params]
  author="K8s-school"
  google_analytics_id="UA-146891246-1"

  [params.homepage_meta_tags]
    meta_description = "K8s School: expertise et formation Kubernetes et Cloud-Natif"
    meta_og_title = "K8s School"
    meta_og_type = "website"
    meta_og_url = "https://k8s-school.fr"
    meta_og_image = "https://k8s-school.fr/images/logo.png"
    meta_og_description = "K8s School fournit une formation Kubernetes pour les micro-services et une formation Kubernetes avancée"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

# Main Menu
# [[menu.main]]
#   name = "Conseil"
#   url = "/conseil/"
#   weight = 1

[[menu.main]]
    name = "Programmes K8s"
    url = "/formations-kubernetes/"
    weight = 2

[[menu.main]]
    name = "Formateurs"
    url = "/team/"
    weight = 3

# [[menu.main]]
#   name = "References"
#   url = "/references/"
#   weight = 4

[[menu.main]]
    name = "Références"
    url = "/references/"
    weight = 5

[[menu.main]]
    name = "Blog FR"
    url = "/resources/fr/blog/"
    weight = 6

[[menu.main]]
    name = "Blog EN"
    url = "/resources/en/blog/"
    weight = 7


[[menu.main]]
    name = "Inscription"
    url = "/limesurvey/index.php/827842"
    weight = 8

# Footer Menu
[[menu.footer]]
    name = "Accueil"
    url = "/"
    weight = 1

[[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 2
