baseURL = "https://k8s-school.fr/"
languageCode = "fr-fr"
title = "K8s-school"
themesDir = "themes"
theme = "hugo-serif-theme"
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[params]
  author="K8s-school"
  google_analytics_id="UA-146891246-1"

  [params.homepage_meta_tags]
    meta_description = "K8s School: expertise et formation Kubernetes et Cloud-Natif"
    meta_og_title = "K8s School"
    meta_og_type = "website"
    meta_og_url = "https://k8s-school.fr"
    meta_og_image = "https://k8s-school.fr/images/logo.png"
    meta_og_description = "K8s School fournit une formation Kubernetes pour les micro-services et une formation Kubernetes avancée"
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

# Main Menu

[[menu.main]]
    name = "S'inscrire"
    url = "https://docs.google.com/forms/d/e/1FAIpQLSdReUtBAMQWI_CuKbSLtEWaIVSlEQKaOMSEnlstjtvS67UnGw/viewform?usp=sf_link"
    weight = 1

[[menu.main]]
    name = "Programmes K8s"
    url = "/formations-kubernetes/"
    weight = 2

[[menu.main]]
    name = "Formateurs"
    url = "/team/"
    weight = 3

[[menu.main]]
    name = "Labs"
    url = "/labs"
    weight = 6

[[menu.main]]
    name = "Références"
    url = "/references/"
    weight = 5

# Footer Menu
[[menu.footer]]
    name = "Accueil"
    url = "/"
    weight = 1

[[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 2
